/**
 * File name: StudentDAO.java
 * Author: Liying Guo, 040858257
 * Course: CST8288 OOP with Design Patterns
 * Assignment: lab2
 * Date: 2024-02-27
 * Professor: Gustavo Adami
 * Purpose: Data Access Object for student table
 */
package org.cst8288Lab2.dao;
import java.sql.SQLException;
import org.cst8288Lab2.dto.StudentDTO;

/**
 * This interface is used for creating, retrieving, updating, and 
 deleting a specific StudentDTO object generated by the Client class; 
 * @author Liying Guo
 * @version 1.0
 * @since 2024-March-03
 */
public interface StudentDAO {
        /***
         * insert student to table
         * @param student to insert
         * @throws SQLException 
         */
	 void createStudent(StudentDTO student) throws SQLException;
        
        /***
         * retrieve student by studentId
         * @param studentId used to query
         * @return
         * @throws SQLException 
         */
         StudentDTO retrieveStudent(int studentId) throws SQLException;
        
        /**
         * update student on table
         * @param student to update
         * @throws SQLException 
         */
         void updateStudent(StudentDTO student) throws SQLException;
        
         void saveStudent(StudentDTO student) throws SQLException;
         void deleteAllRecords() throws SQLException;
}
